name: detoxifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy==1.21.6
  - pandas==1.3.5
  - scikit-learn==0.24.2
  - matplotlib==3.5.1
  - nltk==3.6.7
  - tqdm==4.62.3
  - sentencepiece==0.1.96
  - pip:
      - torch==1.9.1
      - torchvision==0.10.1
      - torchaudio==0.9.1
      - transformers==4.9.2
      - datasets==1.11.0
      - sentence-transformers==2.1.0
      - fairseq==0.10.2
      - fastBPE==0.1.0
      - sacremoses==0.0.53
      - textblob
      - git+https://github.com/bheinzerling/pyrouge.git
